dcterms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.utils.translation import ugettext_lazy as _

import fedoralink_ui.views
from fedoralink.models import FedoraObject

# TODO: zbavit sa model = DCObject, pridat template pre detail collection (search)
urlpatterns = [
    url('^$',
        fedoralink_ui.views.GenericDetailView.as_view(
            fedora_prefix='dcterms'), name="index"),
    url(r'^(?P<collection_id>[a-fA-F0-9_/-]*)extended_search(?P<parameters>.*)$',
        fedoralink_ui.views.GenericSearchView.as_view(
            facets=(),
                                              orderings=(
                                ('title@en', _('Sort by title (asc)')),
                                ('-title@en', _('Sort by title (desc)')),
                        ),
                                              title='Documents',
                                              create_button_title='Create a New Document',
                                              fedora_prefix='dcterms'),
        name='extended_search'),

    url('^(?P<pk>.*)/addSubcollection$', fedoralink_ui.views.GenericSubcollectionCreateView.as_view(
        fedora_prefix='dcterms',
        success_url="dcterms:detail",
        parent_collection=lambda x: FedoraObject.objects.get(pk='dcterms'),
        success_url_param_names=('id',)
    ), name='addSubcollection'),

    url('^(?P<pk>.*)/add$', fedoralink_ui.views.GenericCreateView.as_view(
                                                                              fedora_prefix='dcterms',
                                                                              success_url="dcterms:detail",
                                                                              parent_collection=lambda x: FedoraObject.objects.get(pk='dcterms'),
                                                                              success_url_param_names = ('id',)
                                                                           )
        , name='add'),

    url('^(?P<id>.*)/edit$',
        fedoralink_ui.views.GenericEditView.as_view(
                 success_url="dcterms:detail",
            fedora_prefix='dcterms'
                 ),
        name="edit"),

    url('^(?P<id>.*)$',
        fedoralink_ui.views.GenericDetailView.as_view(
                                              fedora_prefix='dcterms'), name="detail"),
]

urlpatterns = [
    url(r'^', include(urlpatterns, namespace='dcterms', app_name='dcterms'))
]

if settings.USE_BREADCRUMBS:
    import autobreadcrumbs.discover
    autobreadcrumbs.discover.autodiscover()

oarepo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from fedoralink_ui.generic_urls import repository_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^administration/', include("administration.urls")),
    # burl(r'^dcterms/', include("dcterms.urls"), verbose_name=_('DCterms')),
    # url(r'^romiste/', include("romiste.urls")),
    # # url(r'^states/', include("state_engi.ne.urls")),
    # url(r'^types/', include("types_engine.urls")),
    # # url(r'^types/', include("data_types.urls")),
    # url(r'^', include(patterns('',
    #                            url('^$', baseOArepo.views.index, name="index")), namespace='oarepo'))
]

urlpatterns += repository_patterns(app_name="oarepo")

administration/views/datatypes.py
from django.views.generic import TemplateView

from fedoralink.type_manager import FedoraTypeManager
from fedoralink_ui.models import ResourceType


class IndexView(TemplateView):
    template_name = 'oarepo/administration/datatypes/index.html'

    # noinspection PyProtectedMember
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        for model in FedoraTypeManager.models:
            print('model:', model)
            print("    application: ", model._meta.application)
            print("    rdf types: ", model._meta.rdf_types)
            print("    fields: ")
            for field in model._meta.fields:
                print('        %s (%s)' % (field.name, field.rdf_name))

        for rt in ResourceType.objects.all():
            print("resource type: ", rt.label)
            print("    view template", rt.template_view)

            if rt.template_view:
                template_bitstream = rt.template_view.get_bitstream()
                bitstream_data = template_bitstream.stream.read().decode('utf-8')
                print("        ", template_bitstream, bitstream_data[:60].replace('\n', '\\n'))

            print("    edit template", rt.template_edit)
            print("    list item template", rt.template_list_item)

        return context

administration/views/index.py
# Create your views here.
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "oarepo/administration/index.html"

administration/templates/oarepo/administration/index.html
{% extends "web/repository/base.html" %}
{% load i18n %}
{% load l10n %}
{% load fedoralink_tags %}
{% load dcterms_dokumenty %}

{% block title %}Administration - {% endblock %}

{% block head %}
    {{ block.super }}
    <style>
        .cesnet-content {
            min-height: 0px !important;
        }
    </style>
{% endblock %}

{% block left_block %}

{% endblock %}

{% block h1 %}Administration{% endblock %}


{% block widecontent %}
    <div class="container-fluid list-repositories">
        <div class="repository pull-left col-xs-12 col-sm-6 col-md-3">
            <div class="repository-list-item pull-left">
                <div class="repository-header repository-header-disabled"><h4>{% trans "Users, Groups and Access Control" %}</h4></div>
                <div class="repository-detail-small text-muted">
                    Definition of users, groups and access control. Not implemented yet, use REST api for direct
                    manipulation.
                    <a href="{% url 'oarepo:index' %}"
                       class="btn btn-default">{% trans "Show" %}</a>
                </div>
            </div>
        </div>

        <div class="repository pull-left col-xs-12 col-sm-6 col-md-3">
            <div class="repository-list-item pull-left">
                <div class="repository-header"><h4>{% trans "Data States and Approval Processes" %}</h4></div>
                <div class="repository-detail-small">
                    Definition of document states, transitions between them, approval process and associated actions.
                    <a href="/states"
                       class="btn btn-default">{% trans "Show" %}</a>
                </div>
            </div>
        </div>

        <div class="repository pull-left col-xs-12 col-sm-6 col-md-3">
            <div class="repository-list-item pull-left">
                <div class="repository-header repository-header-disabled"><h4>{% trans "Data Types and Collections" %}</h4></div>
                <div class="repository-detail-small text-muted">
                    Definitions of data types and look and feel of collections. Currently defined in python,
                    support for web definitions is under construction.
                    <a href="{% url 'oarepo_administration_datatypes:index' %}"
                       class="btn btn-default btn-disabled">{% trans "Show" %}</a>
                </div>
            </div>
        </div>

    </div>

{% endblock %}